#pragma once
#include <iostream>
#include <string>
#include <vector>
#include <functional>
#include <sstream>
void threedot();
void cls();
void bootanim();
void ensureConsoleInitialized();
void showBootMenu();